webtalk_init -webtalk_dir /home/phanikar/BITS/3-1/DOP/systolic_array_adder/systolic_array_adder.sim/sim_1/behav/xsim/xsim.dir/tb_WSPETOP_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Nov 27 09:51:16 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "62eb44c0-2835-43cb-be1f-c1e0a08ef4d6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "6170063c1394452890efc7582798ee1e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 22.04.5 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3400.113 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "435 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "119092_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2681406200 -regid "" -xml /home/phanikar/BITS/3-1/DOP/systolic_array_adder/systolic_array_adder.sim/sim_1/behav/xsim/xsim.dir/tb_WSPETOP_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/phanikar/BITS/3-1/DOP/systolic_array_adder/systolic_array_adder.sim/sim_1/behav/xsim/xsim.dir/tb_WSPETOP_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/phanikar/BITS/3-1/DOP/systolic_array_adder/systolic_array_adder.sim/sim_1/behav/xsim/xsim.dir/tb_WSPETOP_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
