


///////////////////////////////////////////////////////////////////////////
//NOTE: This file has been automatically generated by Vivado.
///////////////////////////////////////////////////////////////////////////
`timescale 1ps/1ps
package vip_bd_vip_b_0_pkg;
import axi4stream_vip_pkg::*;
///////////////////////////////////////////////////////////////////////////
// These parameters are named after the component for use in your verification 
// environment.
///////////////////////////////////////////////////////////////////////////
      parameter vip_bd_vip_b_0_VIP_INTERFACE_MODE     = 0;
      parameter vip_bd_vip_b_0_VIP_SIGNAL_SET         = 8'b01100011;
      parameter vip_bd_vip_b_0_VIP_DATA_WIDTH         = 256;
      parameter vip_bd_vip_b_0_VIP_ID_WIDTH           = 1;
      parameter vip_bd_vip_b_0_VIP_DEST_WIDTH         = 1;
      parameter vip_bd_vip_b_0_VIP_USER_WIDTH         = 0;
      parameter vip_bd_vip_b_0_VIP_USER_BITS_PER_BYTE = 0;
      parameter vip_bd_vip_b_0_VIP_HAS_TREADY         = 1;
      parameter vip_bd_vip_b_0_VIP_HAS_TSTRB          = 0;
      parameter vip_bd_vip_b_0_VIP_HAS_TKEEP          = 0;
      parameter vip_bd_vip_b_0_VIP_HAS_TLAST          = 0;
      parameter vip_bd_vip_b_0_VIP_HAS_ACLKEN         = 0;
      parameter vip_bd_vip_b_0_VIP_HAS_ARESETN        = 1;
///////////////////////////////////////////////////////////////////////////
typedef axi4stream_mst_agent #(vip_bd_vip_b_0_VIP_SIGNAL_SET, 
                        vip_bd_vip_b_0_VIP_DEST_WIDTH,
                        vip_bd_vip_b_0_VIP_DATA_WIDTH,
                        vip_bd_vip_b_0_VIP_ID_WIDTH,
                        vip_bd_vip_b_0_VIP_USER_WIDTH, 
                        vip_bd_vip_b_0_VIP_USER_BITS_PER_BYTE,
                        vip_bd_vip_b_0_VIP_HAS_ARESETN) vip_bd_vip_b_0_mst_t;
      
///////////////////////////////////////////////////////////////////////////
// How to start the verification component
///////////////////////////////////////////////////////////////////////////
//      vip_bd_vip_b_0_mst_t  vip_bd_vip_b_0_mst;
//      initial begin : START_vip_bd_vip_b_0_MASTER
//        vip_bd_vip_b_0_mst = new("vip_bd_vip_b_0_mst", `vip_bd_vip_b_0_PATH_TO_INTERFACE);
//        vip_bd_vip_b_0_mst.start_master();
//      end



endpackage : vip_bd_vip_b_0_pkg
